name: "Feature request"
description: "Suggest a new feature or improvement"
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: input
    id: summary
    attributes:
      label: "✨ Summary"
      description: "Describe the feature you want."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: "💡 Why is it needed?"
      description: "Explain the use-case or motivation behind this feature."
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: "🧩 Possible approach"
      description: "Outline how this feature might be implemented."

  - type: textarea
    id: context
    attributes:
      label: "📎 Additional context"
      description: "Add screenshots, diagrams, or notes if helpful."
